name: Uninstall Helm chart from EKS cluster
on:
  workflow_dispatch:
jobs:
  uninstall_helm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy Helm
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.12
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
        cluster-name: eks-test
        namespace: otel
        name: my-otel-demo
        action: uninstall
